package com.teessideUni.cfs_tracker.ui.theme


import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val cfsLightPrimary = Color(0xFF825500)
val cfsLightOnPrimary = Color(0xFFFFFFFF)
val cfsLightPrimaryContainer = Color(0xFFFFDDAE)
val cfsLightOnPrimaryContainer = Color(0xFF2A1800)
val cfsLightSecondary = Color(0xFF6F5B40)
val cfsLightOnSecondary = Color(0xFFFFFFFF)
val cfsLightSecondaryContainer = Color(0xFFFADEBC)
val cfsLightOnSecondaryContainer = Color(0xFF271904)
val cfsLightTertiary = Color(0xFF516440)
val cfsLightOnTertiary = Color(0xFFFFFFFF)
val cfsLightTertiaryContainer = Color(0xFFD3EABC)
val cfsLightOnTertiaryContainer = Color(0xFF102004)
val cfsLightError = Color(0xFFBA1B1B)
val cfsLightErrorContainer = Color(0xFFFFDAD4)
val cfsLightOnError = Color(0xFFFFFFFF)
val cfsLightOnErrorContainer = Color(0xFF410001)
val cfsLightBackground = Color(0xFFFCFCFC)
val cfsLightOnBackground = Color(0xFF1F1B16)
val cfsLightSurface = Color(0xFFFCFCFC)
val cfsLightOnSurface = Color(0xFF1F1B16)
val cfsLightSurfaceVariant = Color(0xFFF0E0CF)
val cfsLightOnSurfaceVariant = Color(0xFF4F4539)
val cfsLightOutline = Color(0xFF817567)
val cfsLightInverseOnSurface = Color(0xFFF9EFE6)
val cfsLightInverseSurface = Color(0xFF34302A)
val cfsLightPrimaryInverse = Color(0xFFFFB945)

val cfsDarkPrimary = Color(0xFFFFB945)
val cfsDarkOnPrimary = Color(0xFF452B00)
val cfsDarkPrimaryContainer = Color(0xFF624000)
val cfsDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val cfsDarkSecondary = Color(0xFFDDC3A2)
val cfsDarkOnSecondary = Color(0xFF3E2E16)
val cfsDarkSecondaryContainer = Color(0xFF56442B)
val cfsDarkOnSecondaryContainer = Color(0xFFFADEBC)
val cfsDarkTertiary = Color(0xFFB8CEA2)
val cfsDarkOnTertiary = Color(0xFF243516)
val cfsDarkTertiaryContainer = Color(0xFF3A4C2B)
val cfsDarkOnTertiaryContainer = Color(0xFFD3EABC)
val cfsDarkError = Color(0xFFFFB4A9)
val cfsDarkErrorContainer = Color(0xFF930006)
val cfsDarkOnError = Color(0xFF680003)
val cfsDarkOnErrorContainer = Color(0xFFFFDAD4)
val cfsDarkBackground = Color(0xFF1F1B16)
val cfsDarkOnBackground = Color(0xFFEAE1D9)
val cfsDarkSurface = Color(0xFF1F1B16)
val cfsDarkOnSurface = Color(0xFFEAE1D9)
val cfsDarkSurfaceVariant = Color(0xFF4F4539)
val cfsDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val cfsDarkOutline = Color(0xFF9C8F80)
val cfsDarkInverseOnSurface = Color(0xFF32281A)
val cfsDarkInverseSurface = Color(0xFFEAE1D9)
val cfsDarkPrimaryInverse = Color(0xFF624000)